import type { Metadata } from "next";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v15-appRouter";
import { Roboto } from "next/font/google";
import { ThemeProvider } from "@mui/material/styles";
import CssBaseline from "@mui/material/CssBaseline";
import theme from "../theme";
import { UserProvider } from "./_Components/UserContext/UserContext";
import AppTheme from "./shared-theme/AppTheme";
import { ThemeSettingsProvider } from "./shared-theme/ThemeContext";

import Navbar from "./_Components/Navbar/Navbar";
const roboto = Roboto({
  weight: ["300", "400", "500", "700"],
  subsets: ["latin"],
  display: "swap",
  variable: "--font-roboto",
});

export const metadata: Metadata = {
  title: "Yonna",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
          <head>
      
          <link rel="icon" type="image/jpg" href="/yonna.jpg" />
      </head>
      <body className={`${roboto.variable} `}>
        <AppRouterCacheProvider>
          <ThemeProvider theme={theme}>
            <CssBaseline />
            <UserProvider>
            <Navbar />
           
            <ThemeSettingsProvider disableCustomTheme={false}>
          <AppTheme>
            
              {children}</AppTheme>
              </ThemeSettingsProvider>
            </UserProvider>
          </ThemeProvider>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
